Add Cases for Beta-Reduction of DepApp and for Traversal of DepLambda
elevate-lang/elevate pull request #11
Opened 2020-02-17 09:36 UTC by bastian-koepcke

Adds cases to beta-reduce `DepApp` of kinds other than `Nat`.

Adds a case to enable traversing `DepLambda` of `AddressSpaceKind`

2020-02-17 11:49 UTC, Bastacyclop requested changes
Can we use the same scalatyle config as rise and shine, and not align match cases?
@bastian-koepcke @bastianhagedorn

2020-02-17 14:16 UTC, bastian-koepcke commented
@Bastacyclop I second this. It felt odd to write this style,especially because lines get longer much faster, but I didn't want to decide anything for @bastianhagedorn.

2020-02-18 10:03 UTC, Bastacyclop commented
@bastian-koepcke this will be conflicting with https://github.com/elevate-lang/elevate/pull/12, I propose merging https://github.com/elevate-lang/elevate/pull/12 first and then updating this PR.

2020-02-19 16:31 UTC, Bastacyclop approved these changes

2020-02-19 16:32 UTC, merged